package converter.ecomXslToJson.entities.common;

/**
 * Типы элементов управления.
 */
public enum ControlsType {
    GROUP, INT, STR, FLOAT, BOOL, CURR, WEIGHT, TEXT, PASSWORD, EMAIL,
    BARCODE, ADDRESS, MEN, PATH, FILE, DATE, TIME, DATETIME, DAY, MONTH,
    YEAR, QUATRO, WEEKDAY, PERIODDATE, IMG, POST, KGP, ISBN, INN, KPP,
    INSURANCE, ACCOUNT, BIK, COLOR, PHONE, SELECT, FIND, LIST, SET, TREE,
    LABEL, BTN, HTML, PRINT, EXPORT, TABLE
}
